### PR TITLE
Pantheon cache flush

### PR DESCRIPTION
**Pull request by TrilipuT**
Flush CDN image enge cache on Pantheon hosted websites
co-authored @LogicEveryWhere

### CODE REVIEW

**Comment by pdobrescu** [comment]
Hello @TrilipuT & @LogicEveryWhere and thanks for this PR, it's highly appreciated!

Can you please tell me if you've already tested this and it works on the Pantheon environments (live/staging)?

We'll have a look over it and get back to you ASAP!

**Comment by TrilipuT** [comment]
Hi @pdobrescu !
Sorry for the late reply - we have some things to sort out with russians.

Yes, this is working in LIVE env right now. We refer to [this](https://github.com/pantheon-systems/pantheon-advanced-page-cache/blob/0899aed85d6a1deb5c355e113423ea2b7ccd86c1/pantheon-advanced-page-cache.php#L44) function from Pantheon cache plugin.

**Comment by pdobrescu** [comment]
Thanks for the PR @TrilipuT, we'll include this in 4.22.9 which is due to be released soon. For the upcoming version 5 we have updated a bit our integrations and we'll keep the one with Pantheon but in a slightly different manner.

**Comment by pdobrescu** [comment]
dear @TrilipuT and @LogicEveryWhere, SPIO 5 is out and this integration has slightly been updated. Can you please check that the integration still works as expected? Here's the new code:

https://github.com/short-pixel-optimizer/shortpixel-image-optimiser/blob/master/class/external/pantheon.php

Thanks!

**Pull request merged**
